- release bumbing to force rebuild due to ABI incompatibility:
  Fatal Error: Mismatch between the program and library build versions detected.
  The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
  and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).